describeLoad('DentAI High Concurrency Load Suite - 03_appointments_load.js', () => {
  scenario('LOAD-101: Doctor Available Slot Search Database Query Load (500 VUs, Target Latency < 20ms)', '/api/v1/load/03_appointments/101', 'POST');
  scenario('LOAD-102: Concurrent Slot Reservation Lock Contention Stress (100 VUs on Same Doctor Slot)', '/api/v1/load/03_appointments/102', 'GET');
  scenario('LOAD-103: Appointment Booking Confirmation Transaction Throughput (80 Bookings/sec)', '/api/v1/load/03_appointments/103', 'POST');
  scenario('LOAD-104: Doctor Calendar Monthly Slot Matrix Read Load (400 VUs, Target Latency < 25ms)', '/api/v1/load/03_appointments/104', 'GET');
  scenario('LOAD-105: Appointment Reschedule Slot Swap Concurrency (70 Reschedules/sec)', '/api/v1/load/03_appointments/105', 'POST');
  scenario('LOAD-106: Appointment Cancellation Lock Release Throughput (90 Cancellations/sec)', '/api/v1/load/03_appointments/106', 'GET');
  scenario('LOAD-107: Clinic Geolocation Radius Search Spatial Index Load (250 VUs, Target Latency < 30ms)', '/api/v1/load/03_appointments/107', 'POST');
  scenario('LOAD-108: Insurance Eligibility Verification API Gateway Spike (120 Requests/sec)', '/api/v1/load/03_appointments/108', 'GET');
  scenario('LOAD-109: Appointment Reminder Push Notification Queue Burst (1000 Reminders/sec)', '/api/v1/load/03_appointments/109', 'POST');
  scenario('LOAD-110: Past Appointment History Timeline Query Load (350 VUs, Target Latency < 18ms)', '/api/v1/load/03_appointments/110', 'GET');
  scenario('LOAD-111: Doctor Specialization Filter Query Read Concurrency (600 VUs, Target Latency < 12ms)', '/api/v1/load/03_appointments/111', 'POST');
  scenario('LOAD-112: Telehealth Consultation Session Room Creation Peak (50 Rooms/sec)', '/api/v1/load/03_appointments/112', 'GET');
  scenario('LOAD-113: Emergency Same-Day Priority Slot Lock Stress (110 VUs, Target Latency < 40ms)', '/api/v1/load/03_appointments/113', 'POST');
  scenario('LOAD-114: Appointment Copay Checkout Stripe Webhook Processing (60 Webhooks/sec)', '/api/v1/load/03_appointments/114', 'GET');
  scenario('LOAD-115: Family Multi-Member Appointment Slot Sequence Allocator (40 VUs)', '/api/v1/load/03_appointments/115', 'POST');
  scenario('LOAD-116: Recurring Hygiene Cleaning Reminder Scheduler Load (300 Jobs/min)', '/api/v1/load/03_appointments/116', 'GET');
  scenario('LOAD-117: Pre-Appointment Medical History Upload Payload Stress (30 Uploads/sec)', '/api/v1/load/03_appointments/117', 'POST');
  scenario('LOAD-118: Doctor Profile & Ratings Read Concurrency (700 VUs, Target Latency < 10ms)', '/api/v1/load/03_appointments/118', 'GET');
  scenario('LOAD-119: Virtual Waiting Room Queue Counter Real-Time Updates (500 Connections)', '/api/v1/load/03_appointments/119', 'POST');
  scenario('LOAD-120: Check-In Online Location Proximity Verification Load (200 VUs)', '/api/v1/load/03_appointments/120', 'GET');
  scenario('LOAD-121: Doctor Working Hours Schedule Modification Writes (30 Writes/sec)', '/api/v1/load/03_appointments/121', 'POST');
  scenario('LOAD-122: Doctor Vacation Exclusion Interval Overlap Query Load (220 VUs)', '/api/v1/load/03_appointments/122', 'GET');
  scenario('LOAD-123: Clinic Parking & Directions Metadata Read Concurrency (800 VUs < 5ms)', '/api/v1/load/03_appointments/123', 'POST');
  scenario('LOAD-124: Doctor Language Preference Filter Read Load (450 VUs, Target Latency < 14ms)', '/api/v1/load/03_appointments/124', 'GET');
  scenario('LOAD-125: Waiting List Slot Open Notification Trigger Load (150 Alerts/sec)', '/api/v1/load/03_appointments/125', 'POST');
  scenario('LOAD-126: Patient No-Show Record Audit Writer Throughput (200 Logs/sec)', '/api/v1/load/03_appointments/126', 'GET');
  scenario('LOAD-127: Appointment Confirmation QR Code Generation Load (100 QR/sec)', '/api/v1/load/03_appointments/127', 'POST');
  scenario('LOAD-128: Appointment Confirmation Email Queue Backpressure Stress (200 Emails/sec)', '/api/v1/load/03_appointments/128', 'GET');
  scenario('LOAD-129: Appointment iCal (.ics) Calendar Feed Download Load (300 Downloads/sec)', '/api/v1/load/03_appointments/129', 'POST');
  scenario('LOAD-130: Double-Booking Prevention Database Transaction Retry Benchmark', '/api/v1/load/03_appointments/130', 'GET');
  scenario('LOAD-131: Appointment Database Connection Pool Saturation Test (300 Connections)', '/api/v1/load/03_appointments/131', 'POST');
  scenario('LOAD-132: Appointment Service Burst Stress (0 to 350 VUs in 4 Seconds)', '/api/v1/load/03_appointments/132', 'GET');
  scenario('LOAD-133: Appointment Service Endurance Benchmark (200 VUs for 20 Minutes)', '/api/v1/load/03_appointments/133', 'POST');
  scenario('LOAD-134: Appointment API Cache Invalidation Storm Verification', '/api/v1/load/03_appointments/134', 'GET');
  scenario('LOAD-135: Appointment Search Pagination Cursor Read Throughput (400 VUs)', '/api/v1/load/03_appointments/135', 'POST');
  scenario('LOAD-136: Appointment Status Change Webhook Delivery Stress (120 Events/sec)', '/api/v1/load/03_appointments/136', 'GET');
  scenario('LOAD-137: Appointment Receipts PDF Invoice Export Queue Load (35 PDFs/sec)', '/api/v1/load/03_appointments/137', 'POST');
  scenario('LOAD-138: Appointment Timezone Offset Shift Converter Load (600 Requests/sec)', '/api/v1/load/03_appointments/138', 'GET');
  scenario('LOAD-139: Telehealth Video Session Token Expiration Revocation Load (180 VUs)', '/api/v1/load/03_appointments/139', 'POST');
  scenario('LOAD-140: Doctor Patient Rating Score Aggregator Database Read (300 VUs)', '/api/v1/load/03_appointments/140', 'GET');
  scenario('LOAD-141: Clinic Operating Status Evaluator Read Load (1000 Requests/sec)', '/api/v1/load/03_appointments/141', 'POST');
  scenario('LOAD-142: Appointment Pre-Visit Health Survey Submit Throughput (90 Submits/sec)', '/api/v1/load/03_appointments/142', 'GET');
  scenario('LOAD-143: Appointment Attachment Storage Upload Stress (25 Uploads/sec)', '/api/v1/load/03_appointments/143', 'POST');
  scenario('LOAD-144: Doctor Specialty Category List Cache Hit Ratio (900 VUs < 5ms)', '/api/v1/load/03_appointments/144', 'GET');
  scenario('LOAD-145: Appointment Discount Coupon Code Validation Spike (150 Validations/sec)', '/api/v1/load/03_appointments/145', 'POST');
  scenario('LOAD-146: Appointment Cancellation Refund Processing Queue Load (40 Refunds/sec)', '/api/v1/load/03_appointments/146', 'GET');
  scenario('LOAD-147: Appointment Re-booking Fast Shortcut Throughput (130 Bookings/sec)', '/api/v1/load/03_appointments/147', 'POST');
  scenario('LOAD-148: Appointment Notification SMS Resend Request Load (160 Requests/sec)', '/api/v1/load/03_appointments/148', 'GET');
  scenario('LOAD-149: Appointment System Cold Start Warm-Up Benchmark', '/api/v1/load/03_appointments/149', 'POST');
  scenario('LOAD-150: Appointment System Zero-Error High-Throughput Certification', '/api/v1/load/03_appointments/150', 'GET');
});
