describeLoad('DentAI High Concurrency Load Suite - 04_ai_chat_load.js', () => {
  scenario('LOAD-151: High Concurrency SSE Chat Response Streaming (300 Concurrent Socket Streams)', '/api/v1/chat/stream', 'POST');
  scenario('LOAD-152: LLM AI Gateway Rate Limiter & Prompt Processing Load (50 Queries/sec)', '/api/v1/chat/message', 'POST');
  scenario('LOAD-153: Chat Session History Database Query Peak (400 VUs, Target Latency < 22ms)', '/api/v1/chat/conversations', 'GET');
  scenario('LOAD-154: AI System Prompt Token Counter & Window Trimmer Stress (200 Requests/sec)', '/api/v1/chat/token-counter', 'POST');
  scenario('LOAD-155: Chat Image Attachment Vision Preprocessing Queue Load (30 Images/sec)', '/api/v1/chat/upload-image', 'POST');
  scenario('LOAD-156: Voice Audio Speech-to-Text Transcription Gateway Load (25 Audio Files/sec)', '/api/v1/chat/stt-transcribe', 'POST');
  scenario('LOAD-157: Text-to-Speech Audio Generation Stream Throughput (20 Audio Streams/sec)', '/api/v1/chat/tts-generate', 'POST');
  scenario('LOAD-158: Suggested Prompt Chips Generator Read Concurrency (600 VUs, Target Latency < 10ms)', '/api/v1/chat/suggested-prompts', 'GET');
  scenario('LOAD-159: Chat Response Feedback Thumbs Up/Down Writes (150 Feedback Writes/sec)', '/api/v1/chat/feedback', 'POST');
  scenario('LOAD-160: Regenerate AI Response Queue Backpressure Load (35 Regenerations/sec)', '/api/v1/chat/regenerate', 'POST');
  scenario('LOAD-161: Search Chat History Keyword Indexing Database Load (180 VUs, Target Latency < 35ms)', '/api/v1/chat/search', 'GET');
  scenario('LOAD-162: Export Chat Transcript PDF Generation Queue Load (30 PDFs/sec)', '/api/v1/chat/export-pdf', 'POST');
  scenario('LOAD-163: Export Chat Transcript Markdown Generator Load (250 Conversions/sec)', '/api/v1/chat/export-markdown', 'POST');
  scenario('LOAD-164: Emergency Keyword Scanner High-Speed Filter (1000 Text Messages/sec)', '/api/v1/chat/scan-emergency', 'POST');
  scenario('LOAD-165: Medical Terminology Glossary Lookup Cache Hit Ratio (800 VUs < 5ms)', '/api/v1/chat/glossary', 'GET');
  scenario('LOAD-166: Medication Dosage Caution Alert Evaluation Engine (300 Messages/sec)', '/api/v1/chat/check-dosage', 'POST');
  scenario('LOAD-167: Direct Book Appointment Action Trigger from Chat (40 Bookings/sec)', '/api/v1/chat/book-direct', 'POST');
  scenario('LOAD-168: Clear Active Chat Thread Database Deletion Throughput (100 Deletions/sec)', '/api/v1/chat/clear-thread', 'DELETE');
  scenario('LOAD-169: System Prompt Persona Switcher Payload Load (200 Switches/sec)', '/api/v1/chat/persona-switch', 'POST');
  scenario('LOAD-170: Token Count Hourly Cap Bucket Enforcement Stress (500 Requests/sec)', '/api/v1/chat/check-cap', 'GET');
  scenario('LOAD-171: Markdown Renderer Output Sanitizer Processing Throughput (450 Messages/sec)', '/api/v1/chat/sanitize-md', 'POST');
  scenario('LOAD-172: LLM API Timeout Fallback Response Handler Benchmark', '/api/v1/chat/fallback-test', 'POST');
  scenario('LOAD-173: Chat Socket Disconnect & Reconnect Retry Storm Stress (200 Reconnections/sec)', '/api/v1/chat/reconnect', 'POST');
  scenario('LOAD-174: Unread Message Counter Database Read Concurrency (700 VUs, Target Latency < 8ms)', '/api/v1/chat/unread-count', 'GET');
  scenario('LOAD-175: Multi-Line Message Text Processing Load (350 Messages/sec)', '/api/v1/chat/multiline-parse', 'POST');
  scenario('LOAD-176: Chat Special Character & Emoji Processing Speed (600 Messages/sec)', '/api/v1/chat/emoji-parse', 'POST');
  scenario('LOAD-177: Dark Mode Theme Chat Styling Render Benchmark (1000 Views/sec)', '/api/v1/chat/theme-config', 'GET');
  scenario('LOAD-178: Offline Chat Queue Batch Sync on Reconnect Throughput (150 Syncs/sec)', '/api/v1/chat/batch-sync', 'POST');
  scenario('LOAD-179: Chat Socket Data TLS Encryption Overhead Test (250 Open TLS Connections)', '/api/v1/chat/tls-check', 'GET');
  scenario('LOAD-180: Report Inappropriate AI Response Audit Writer Load (50 Reports/sec)', '/api/v1/chat/report-abuse', 'POST');
  scenario('LOAD-181: Chat Session Resume State Deserialization Load (300 Sessions/sec)', '/api/v1/chat/resume-session', 'POST');
  scenario('LOAD-182: LLM Token Usage Metrics Collector Throughput (400 Metric Logs/sec)', '/api/v1/chat/log-metrics', 'POST');
  scenario('LOAD-183: Chat Thread Rename Inline Update Throughput (120 Updates/sec)', '/api/v1/chat/rename-thread', 'PUT');
  scenario('LOAD-184: Chat Thread Sidebar List Read Concurrency (500 VUs, Target Latency < 15ms)', '/api/v1/chat/threads', 'GET');
  scenario('LOAD-185: AI Persona System Instruction Cache Hit Ratio (900 VUs < 5ms)', '/api/v1/chat/personas', 'GET');
  scenario('LOAD-186: Chat Attachment File Size Limit Enforcement Load (300 Checks/sec)', '/api/v1/chat/check-file-size', 'POST');
  scenario('LOAD-187: Voice Message Waveform Array Processing Speed (200 Waveforms/sec)', '/api/v1/chat/process-waveform', 'POST');
  scenario('LOAD-188: Chat Audio Playback Speed Multiplier Transformer (400 Streams/sec)', '/api/v1/chat/speed-transform', 'POST');
  scenario('LOAD-189: Chat Message Copy to Clipboard Telemetry Event Load (500 Events/sec)', '/api/v1/chat/clipboard-event', 'POST');
  scenario('LOAD-190: Chat Message External Share Intent Processor (100 Shares/sec)', '/api/v1/chat/share-intent', 'POST');
  scenario('LOAD-191: Chat Code Block Formatting Processor Speed (300 Blocks/sec)', '/api/v1/chat/format-code', 'POST');
  scenario('LOAD-192: Chat Hyperlink Extractor & Sanitizer Throughput (500 Hyperlinks/sec)', '/api/v1/chat/sanitize-links', 'POST');
  scenario('LOAD-193: Chat Socket Ping/Pong Keep-Alive Heartbeat Concurrency (1000 Sockets)', '/api/v1/chat/heartbeat', 'POST');
  scenario('LOAD-194: Chat Memory Leaks Monitor during Sustained 30-Minute Load', '/api/v1/chat/mem-check', 'GET');
  scenario('LOAD-195: Chat High Concurrency Burst (0 to 400 Active Streaming Sessions in 5s)', '/api/v1/chat/burst-stream', 'POST');
  scenario('LOAD-196: Chat Gateway Response Time Percentile Benchmark (p95 < 120ms)', '/api/v1/chat/p95-bench', 'GET');
  scenario('LOAD-197: Chat Response Compression Bandwidth Saving Benchmark (Gzip/Brotli)', '/api/v1/chat/compress-check', 'GET');
  scenario('LOAD-198: Chat Database Write Pool Stress on Long Conversations (100 Messages/thread)', '/api/v1/chat/long-thread-save', 'POST');
  scenario('LOAD-199: Chat Service Recovery after simulated LLM Provider Outage', '/api/v1/chat/recovery-check', 'GET');
  scenario('LOAD-200: Chat Gateway Zero-Failure High Concurrency Certification Benchmark', '/api/v1/chat/health', 'GET');
});
