describeLoad('DentAI High Concurrency Load Suite - 05_dental_scan_load.js', () => {
  scenario('LOAD-201: Intraoral Radiograph Multipart Upload Load (20 Uploads/sec, 10MB Files)', '/api/v1/scan/upload', 'POST');
  scenario('LOAD-202: DICOM File Standard Header Parser Concurrency (30 DICOM Files/sec)', '/api/v1/scan/parse-dicom', 'POST');
  scenario('LOAD-203: AI Cavity Detection Image Segmentation Queue Load (15 Scans/sec)', '/api/v1/scan/segment-cavities', 'POST');
  scenario('LOAD-204: Tartar & Plaque Overlay Mask Generation Throughput (18 Scans/sec)', '/api/v1/scan/plaque-mask', 'POST');
  scenario('LOAD-205: Gingivitis Inflammation Red Channel Segmentation Load (20 Scans/sec)', '/api/v1/scan/gingivitis-mask', 'POST');
  scenario('LOAD-206: Enamel Micro-Crack AI Annotation Pipeline Speed (25 Scans/sec)', '/api/v1/scan/crack-trace', 'POST');
  scenario('LOAD-207: Tooth Bounding Box Label Classification Load (35 Scans/sec)', '/api/v1/scan/classify-teeth', 'POST');
  scenario('LOAD-208: Scan Confidence Score Calculation Engine Speed (100 Calculations/sec)', '/api/v1/scan/confidence-score', 'POST');
  scenario('LOAD-209: High Risk Finding Alert Webhook Notification Burst (50 Alerts/sec)', '/api/v1/scan/alert-webhook', 'POST');
  scenario('LOAD-210: Side-by-Side Dual Scan Comparison Image Fetch Load (150 Fetch/sec)', '/api/v1/scan/compare-images', 'GET');
  scenario('LOAD-211: Export Annotated Radiograph Image High-Res Render (12 Renders/sec)', '/api/v1/scan/render-annotated', 'POST');
  scenario('LOAD-212: Download Comprehensive Scan Analysis PDF Queue Load (25 PDFs/sec)', '/api/v1/scan/pdf-report', 'GET');
  scenario('LOAD-213: Share Scan Findings Email Link Resolution Load (200 VUs)', '/api/v1/scan/share-link', 'GET');
  scenario('LOAD-214: DICOM Windowing & Leveling Contrast Processing Speed (80 Requests/sec)', '/api/v1/scan/dicom-windowing', 'POST');
  scenario('LOAD-215: Measure Distance Metric Millimeter Converter Load (500 Calculations/sec)', '/api/v1/scan/convert-distance', 'POST');
  scenario('LOAD-216: Tooth FDI Numbering Overlay Transformer Speed (300 Overlays/sec)', '/api/v1/scan/fdi-overlay', 'POST');
  scenario('LOAD-217: Scan Quality Blurry Image Assessor Pipeline Speed (40 Photos/sec)', '/api/v1/scan/assess-quality', 'POST');
  scenario('LOAD-218: Incisor View Camera Mode Preprocessor Speed (50 Photos/sec)', '/api/v1/scan/incisor-prep', 'POST');
  scenario('LOAD-219: Molar View Camera Mode Preprocessor Speed (50 Photos/sec)', '/api/v1/scan/molar-prep', 'POST');
  scenario('LOAD-220: Panoramic OPG Radiograph Processing Pipeline Speed (8 Scans/sec)', '/api/v1/scan/opg-process', 'POST');
  scenario('LOAD-221: 3D CBCT Scan Volume Slice Navigation Stream Load (10 Streams/sec)', '/api/v1/scan/cbct-stream', 'GET');
  scenario('LOAD-222: Invert Negative Film Image Filter Processing Speed (120 Filters/sec)', '/api/v1/scan/invert-negative', 'POST');
  scenario('LOAD-223: Magnifying Glass Lens Crop Sub-Array Generator Speed (200 Crops/sec)', '/api/v1/scan/crop-magnify', 'POST');
  scenario('LOAD-224: Save Scan to Patient Record Library Write Throughput (60 Scans/sec)', '/api/v1/scan/save-record', 'POST');
  scenario('LOAD-225: Filter Saved Scans Date Range Query Load (300 VUs, Target Latency < 20ms)', '/api/v1/scan/filter-scans', 'GET');
  scenario('LOAD-226: Delete Scan File Audit Trail Verification Throughput (40 Deletions/sec)', '/api/v1/scan/delete-file', 'DELETE');
  scenario('LOAD-227: Print Scan Summary Sheet PDF Converter Load (20 PDFs/sec)', '/api/v1/scan/print-summary', 'GET');
  scenario('LOAD-228: AI Vision Model Architecture Specs Read Concurrency (800 VUs < 5ms)', '/api/v1/scan/model-specs', 'GET');
  scenario('LOAD-229: Second Opinion Request Doctor Notification Trigger Load (30 Notifications/sec)', '/api/v1/scan/second-opinion', 'POST');
  scenario('LOAD-230: Batch Radiograph Series Upload Queue Backlog Load (5 Batch Uploads/sec)', '/api/v1/scan/batch-upload', 'POST');
  scenario('LOAD-231: Vision AI Queue Worker Concurrency Threshold Stress (8 Parallel Workers)', '/api/v1/scan/worker-stress', 'POST');
  scenario('LOAD-232: Vision AI GPU Task Scheduler Queue Backpressure Load', '/api/v1/scan/gpu-schedule', 'POST');
  scenario('LOAD-233: Vision Image Aspect Ratio Normalizer Processing Speed (150 Images/sec)', '/api/v1/scan/aspect-normalize', 'POST');
  scenario('LOAD-234: Vision Image Brightness/Contrast Adjustment Filter Speed (100 Filters/sec)', '/api/v1/scan/adjust-contrast', 'POST');
  scenario('LOAD-235: Vision Image Crop Sub-Region Slice Extractor Speed (120 Crops/sec)', '/api/v1/scan/slice-crop', 'POST');
  scenario('LOAD-236: Vision Image Color Histogram Calculation Speed (200 Histograms/sec)', '/api/v1/scan/color-histogram', 'POST');
  scenario('LOAD-237: Vision Image Sharpness Laplacian Score Filter Speed (90 Images/sec)', '/api/v1/scan/sharpness-score', 'POST');
  scenario('LOAD-238: Vision Image IoU Bounding Box Overlap Evaluator Speed (300 Evaluators/sec)', '/api/v1/scan/iou-eval', 'POST');
  scenario('LOAD-239: Vision Image Thumbnail 128x128 Generator Load (60 Thumbnails/sec)', '/api/v1/scan/thumbnail-gen', 'POST');
  scenario('LOAD-240: Vision Image PNG/JPEG Encoder Compression Speed (40 Encodings/sec)', '/api/v1/scan/compress-encode', 'POST');
  scenario('LOAD-241: Vision Image Base64 String Decoder Processing Speed (80 Decodings/sec)', '/api/v1/scan/decode-base64', 'POST');
  scenario('LOAD-242: Vision Image SHA-256 Checksum Hash Verifier Speed (400 Hashes/sec)', '/api/v1/scan/hash-verify', 'POST');
  scenario('LOAD-243: Vision Image Exif Metadata Stripper Speed (300 Strips/sec)', '/api/v1/scan/strip-exif', 'POST');
  scenario('LOAD-244: Vision Image MIME Type Magic Bytes Verifier Speed (1000 Checks/sec)', '/api/v1/scan/magic-bytes', 'POST');
  scenario('LOAD-245: Vision Image Watermark Text Canvas Overlay Speed (70 Watermarks/sec)', '/api/v1/scan/watermark-overlay', 'POST');
  scenario('LOAD-246: Vision Image Memory Consumption Benchmark under Heavy 10MB Files', '/api/v1/scan/mem-benchmark', 'GET');
  scenario('LOAD-247: Vision Image Storage S3/Cloud Bucket Upload Gateway Stress', '/api/v1/scan/s3-gateway-stress', 'POST');
  scenario('LOAD-248: Vision Image Processing Latency Percentile Benchmark (p95 < 450ms)', '/api/v1/scan/p95-latency', 'GET');
  scenario('LOAD-249: Vision Image Processing Failure Recovery & Retry Queue Benchmark', '/api/v1/scan/retry-queue', 'POST');
  scenario('LOAD-250: Vision Scan Service Zero-Error High Volume Certification Benchmark', '/api/v1/scan/health', 'GET');
});
