describeLoad('DentAI High Concurrency Load Suite - 06_education_feed_load.js', () => {
  scenario('LOAD-251: Education Article Search Index Query Throughput (400 VUs, Target Latency < 25ms)', '/api/v1/education/search', 'GET');
  scenario('LOAD-252: Preventative Care Category Feed Read Cache Hit Ratio (800 VUs < 5ms)', '/api/v1/education/feed/preventative', 'GET');
  scenario('LOAD-253: Pediatric Dental Health Article Feed Load (600 VUs, Target Latency < 10ms)', '/api/v1/education/feed/pediatric', 'GET');
  scenario('LOAD-254: Cosmetic Dentistry Category Feed Read Load (550 VUs, Target Latency < 12ms)', '/api/v1/education/feed/cosmetic', 'GET');
  scenario('LOAD-255: Periodontal Care Category Feed Read Load (500 VUs, Target Latency < 14ms)', '/api/v1/education/feed/periodontal', 'GET');
  scenario('LOAD-256: Article Bookmark Write Throughput (200 Bookmarks/sec)', '/api/v1/education/bookmark', 'POST');
  scenario('LOAD-257: Article Bookmark Remove Throughput (220 Removals/sec)', '/api/v1/education/bookmark', 'DELETE');
  scenario('LOAD-258: Article Social Share Token Resolution Load (350 VUs, Target Latency < 15ms)', '/api/v1/education/share-token', 'GET');
  scenario('LOAD-259: Text-to-Speech Audio Article Stream Throughput (30 Streams/sec)', '/api/v1/education/tts-stream', 'GET');
  scenario('LOAD-260: Video Tutorial Embed Metadata Fetch Load (700 VUs < 8ms)', '/api/v1/education/video-meta', 'GET');
  scenario('LOAD-261: Interactive Hygiene Quiz Submit & Score Engine (150 Quizzes/sec)', '/api/v1/education/quiz-score', 'POST');
  scenario('LOAD-262: Daily Dental Care Tip Card Read Cache Hit Ratio (1000 VUs < 4ms)', '/api/v1/education/daily-tip', 'GET');
  scenario('LOAD-263: Download Care Infographic PDF Queue Load (40 PDFs/sec)', '/api/v1/education/pdf-infographic', 'GET');
  scenario('LOAD-264: Doctor Analytics Dashboard Patient Volume Query Load (200 VUs, Target Latency < 35ms)', '/api/v1/analytics/patient-volume', 'GET');
  scenario('LOAD-265: Doctor Analytics Common Diagnoses Pie Chart Aggregation (180 VUs)', '/api/v1/analytics/diagnoses-pie', 'GET');
  scenario('LOAD-266: Doctor Analytics Cancellation Rate Metric Calculation (220 VUs)', '/api/v1/analytics/cancellation-rate', 'GET');
  scenario('LOAD-267: Doctor Analytics Patient Satisfaction Rating Query (250 VUs)', '/api/v1/analytics/satisfaction-rating', 'GET');
  scenario('LOAD-268: Export Analytics CSV Spreadsheet Generator Load (30 CSVs/sec)', '/api/v1/analytics/export-csv', 'GET');
  scenario('LOAD-269: Export Analytics High-Res Chart Image Generator (20 PNGs/sec)', '/api/v1/analytics/export-png', 'GET');
  scenario('LOAD-270: Clinic KPI Summary Widget Aggregator Query Load (300 VUs)', '/api/v1/analytics/kpi-summary', 'GET');
  scenario('LOAD-271: Patient Age Demographic Chart Aggregation Query Load (210 VUs)', '/api/v1/analytics/age-demographics', 'GET');
  scenario('LOAD-272: Treatment Revenue Performance Chart Database Read (190 VUs)', '/api/v1/analytics/revenue-chart', 'GET');
  scenario('LOAD-273: Weekly No-Show Trends Line Chart Aggregator (230 VUs)', '/api/v1/analytics/noshow-trends', 'GET');
  scenario('LOAD-274: Patient Portal Usage Telemetry Chart Aggregator (240 VUs)', '/api/v1/analytics/portal-telemetry', 'GET');
  scenario('LOAD-275: High Risk Patient Alert List Read Concurrency (400 VUs)', '/api/v1/analytics/high-risk-list', 'GET');
  scenario('LOAD-276: System Audit Trail Log List Pagination Read Throughput (300 VUs)', '/api/v1/audit/logs-page', 'GET');
  scenario('LOAD-277: Filter Audit Log Action Type Query Load (350 VUs)', '/api/v1/audit/filter-action', 'GET');
  scenario('LOAD-278: Export Audit Log CSV for HIPAA Compliance Load (25 CSVs/sec)', '/api/v1/audit/export-hipaa-csv', 'GET');
  scenario('LOAD-279: Notification Center Unread Alert Count Read Load (800 VUs < 6ms)', '/api/v1/notifications/unread-badge', 'GET');
  scenario('LOAD-280: Notification Push Preferences Toggle Writes (180 Writes/sec)', '/api/v1/notifications/push-settings', 'PUT');
  scenario('LOAD-281: Email Notification Frequency Option Change Writes (160 Writes/sec)', '/api/v1/notifications/email-settings', 'PUT');
  scenario('LOAD-282: SMS Notification Preferences Management Writes (170 Writes/sec)', '/api/v1/notifications/sms-settings', 'PUT');
  scenario('LOAD-283: Push Notification Browser Channel Subscription Load (250 Subscriptions/sec)', '/api/v1/notifications/browser-subscribe', 'POST');
  scenario('LOAD-284: Dark / Light Theme Toggle State Sync Load (600 Requests/sec)', '/api/v1/user/theme-sync', 'POST');
  scenario('LOAD-285: Font Size Scaler Preference Save Throughput (500 Requests/sec)', '/api/v1/user/font-scale', 'POST');
  scenario('LOAD-286: Accessibility High Contrast Setting Save Throughput (500 Requests/sec)', '/api/v1/user/high-contrast', 'POST');
  scenario('LOAD-287: Footer Privacy Policy Content Read Cache Hit Ratio (1200 VUs < 3ms)', '/api/v1/content/privacy-policy', 'GET');
  scenario('LOAD-288: System Health Status Monitor Ping Load (1500 Requests/sec)', '/api/v1/system/ping-all', 'GET');
  scenario('LOAD-289: Feedback Rating Submission Form Writes (120 Submissions/sec)', '/api/v1/feedback/submit', 'POST');
  scenario('LOAD-290: Release Notes & Version Info Read Cache Hit Ratio (1000 VUs < 4ms)', '/api/v1/system/release-notes', 'GET');
  scenario('LOAD-291: Redis Cache Invalidation Benchmark on Article Content Update', '/api/v1/education/invalidate-cache', 'POST');
  scenario('LOAD-292: Database Connection Pool Load under Combined Analytics Queries', '/api/v1/analytics/db-stress', 'GET');
  scenario('LOAD-293: Feed & Analytics Burst Load (0 to 500 VUs in 3 Seconds)', '/api/v1/analytics/burst-load', 'GET');
  scenario('LOAD-294: Feed & Analytics Endurance Load (250 VUs for 20 Minutes)', '/api/v1/analytics/endurance', 'GET');
  scenario('LOAD-295: Feed & Analytics API Response Latency Percentiles (p95 < 28ms)', '/api/v1/analytics/latency-check', 'GET');
  scenario('LOAD-296: Feed & Analytics Bandwidth Compression Efficiency Benchmark (Brotli)', '/api/v1/analytics/brotli-check', 'GET');
  scenario('LOAD-297: Feed & Analytics Memory Leak Check during High Volume Browsing', '/api/v1/analytics/mem-check', 'GET');
  scenario('LOAD-298: Feed & Analytics Cold Start Warm-Up Benchmark', '/api/v1/analytics/warmup', 'GET');
  scenario('LOAD-299: Feed & Analytics Multi-Tenant Isolation Throughput Assertion', '/api/v1/analytics/tenant-isolation', 'GET');
  scenario('LOAD-300: Educational Feed & Analytics Zero-Failure Certification Benchmark', '/api/v1/education/health', 'GET');
});
