const fs = require('fs');
const path = require('path');

const scenariosDir = path.join(__dirname, 'scenarios');

// 300 Completely Unique Load Test Specs with explicit endpoints, methods, VU concurrency & RPS targets
const loadTopics = [
  // 001 - 050: Auth Load
  { name: 'Concurrent Patient OAuth Login Burst (50 VUs, Target Latency < 45ms)', path: '/api/v1/auth/login', method: 'POST' },
  { name: 'Registration Endpoint High Throughput Stress (100 VUs, Target Latency < 60ms)', path: '/api/v1/auth/register', method: 'POST' },
  { name: 'JWT Refresh Token Rotation Concurrency Peak (150 VUs, Target Latency < 25ms)', path: '/api/v1/auth/refresh', method: 'POST' },
  { name: 'Password Reset Token Request Flood (200 VUs, Target Latency < 35ms)', path: '/api/v1/auth/password-reset-request', method: 'POST' },
  { name: 'Two-Factor TOTP Code Verification Spike (250 VUs, Target Latency < 20ms)', path: '/api/v1/auth/verify-2fa', method: 'POST' },
  { name: 'User Session Validation Middleware Load (300 VUs, Target Latency < 10ms)', path: '/api/v1/auth/session-check', method: 'GET' },
  { name: 'Account Logout Session Revocation Stress (100 VUs, Target Latency < 15ms)', path: '/api/v1/auth/logout', method: 'POST' },
  { name: 'Google OAuth Callback Gateway Load (120 VUs, Target Latency < 50ms)', path: '/api/v1/auth/oauth/google', method: 'GET' },
  { name: 'Apple Sign-In Token Exchange Concurrency (140 VUs, Target Latency < 55ms)', path: '/api/v1/auth/oauth/apple', method: 'POST' },
  { name: 'Invalid Credential Brute-Force Rate Limiter Bucket Stress (500 Requests/sec)', path: '/api/v1/auth/login', method: 'POST' },
  { name: 'Account Profile Update Concurrent Writes (80 VUs, Target Latency < 40ms)', path: '/api/v1/user/profile', method: 'PUT' },
  { name: 'Avatar Upload Storage Gateway Multipart Stress (30 VUs, 5MB File Payload)', path: '/api/v1/user/avatar', method: 'POST' },
  { name: 'Active Sessions List Read Concurrency (250 VUs, Target Latency < 18ms)', path: '/api/v1/user/sessions', method: 'GET' },
  { name: 'Remote Session Revocation Signal Flood (90 VUs, Target Latency < 22ms)', path: '/api/v1/user/sessions/revoke', method: 'DELETE' },
  { name: 'Password Change Hash Calculation CPU Endurance Stress (60 VUs, Argon2 Hash)', path: '/api/v1/user/change-password', method: 'POST' },
  { name: 'Captcha Validation Token Verification Load (180 VUs, Target Latency < 30ms)', path: '/api/v1/auth/verify-captcha', method: 'POST' },
  { name: 'User Security Event Audit Log Writer Load (400 Requests/sec)', path: '/api/v1/audit/security-event', method: 'POST' },
  { name: 'CORS Preflight OPTIONS Request Burst (1000 Requests/sec)', path: '/api/v1/auth/login', method: 'OPTIONS' },
  { name: 'Mobile WebAuthn Passkey Registration Payload Stress (70 VUs, Target Latency < 35ms)', path: '/api/v1/auth/passkey/register', method: 'POST' },
  { name: 'WebAuthn Assertion Authentication Spike (110 VUs, Target Latency < 30ms)', path: '/api/v1/auth/passkey/authenticate', method: 'POST' },
  { name: 'Role Permission Cache Verification Latency Test (500 VUs, Target Latency < 5ms)', path: '/api/v1/auth/permissions', method: 'GET' },
  { name: 'Account Lockout Recovery Token Verification (50 VUs, Target Latency < 25ms)', path: '/api/v1/auth/unlock-account', method: 'POST' },
  { name: 'SMS OTP Trigger Queue Backpressure Stress (150 SMS/sec)', path: '/api/v1/auth/send-otp', method: 'POST' },
  { name: 'SMS OTP Verification High-Speed Match (200 VUs, Target Latency < 20ms)', path: '/api/v1/auth/verify-otp', method: 'POST' },
  { name: 'Email Verification Link Token Resolution Load (300 VUs, Target Latency < 15ms)', path: '/api/v1/auth/verify-email', method: 'GET' },
  { name: 'User Preference State Sync Writes (100 VUs, Target Latency < 20ms)', path: '/api/v1/user/preferences', method: 'PUT' },
  { name: 'User Preference State Read Cache Hit Rate (600 VUs, Target Latency < 8ms)', path: '/api/v1/user/preferences', method: 'GET' },
  { name: 'Account Privacy Consent Flag Toggle Stress (90 VUs, Target Latency < 22ms)', path: '/api/v1/user/consent', method: 'POST' },
  { name: 'Account Deletion Request Queue Backlog Load (30 VUs, Target Latency < 50ms)', path: '/api/v1/user/delete-account', method: 'POST' },
  { name: 'Multi-Tenant Authorization Header Parsing Load (450 VUs, Target Latency < 12ms)', path: '/api/v1/tenant/auth-check', method: 'GET' },
  { name: 'Rate Limiter Sliding Window Redis Memory Stress (800 Requests/sec)', path: '/api/v1/auth/rate-limit-check', method: 'GET' },
  { name: 'Auth Service Endurance Test (200 VUs Sustained for 10 Minutes)', path: '/api/v1/auth/ping', method: 'GET' },
  { name: 'Auth Service Spike Load (0 to 400 VUs in 5 Seconds)', path: '/api/v1/auth/login', method: 'POST' },
  { name: 'Auth Service Ramp-Down Latency Recovery Benchmark', path: '/api/v1/auth/session-check', method: 'GET' },
  { name: 'Patient Emergency Contact Update Concurrency (75 VUs, Target Latency < 30ms)', path: '/api/v1/user/emergency-contact', method: 'PUT' },
  { name: 'FCM Push Registration Token Bulk Update (130 VUs, Target Latency < 25ms)', path: '/api/v1/notifications/fcm-token', method: 'POST' },
  { name: 'APNs Token Register Payload Compression Stress (110 VUs, Target Latency < 25ms)', path: '/api/v1/notifications/apns-token', method: 'POST' },
  { name: 'User Language Locale Change Broadcast (160 VUs, Target Latency < 18ms)', path: '/api/v1/user/locale', method: 'PUT' },
  { name: 'Account Lockout Status Check Concurrency (220 VUs, Target Latency < 14ms)', path: '/api/v1/auth/lockout-status', method: 'GET' },
  { name: 'Health Check Endpoint High Frequency Ping (1200 Requests/sec)', path: '/health', method: 'GET' },
  { name: 'SSL/TLS Handshake Overhead Benchmark (100 New Connections/sec)', path: '/api/v1/auth/login', method: 'POST' },
  { name: 'HTTP/2 Multiplexing Stream Concurrency (250 Streams per Connection)', path: '/api/v1/auth/session-check', method: 'GET' },
  { name: 'Database Auth Connection Pool Saturation Threshold Stress', path: '/api/v1/auth/login', method: 'POST' },
  { name: 'User Account Status Search Cache Hit Ratio Benchmark (500 VUs)', path: '/api/v1/user/status', method: 'GET' },
  { name: 'Token Revocation List (TRL) Redis Lookup Latency (600 VUs < 5ms)', path: '/api/v1/auth/check-revocation', method: 'GET' },
  { name: 'Bulk User Role Verification Endpoint Stress (90 VUs, Target Latency < 35ms)', path: '/api/v1/auth/bulk-role-check', method: 'POST' },
  { name: 'Patient HIPAA Data Consent Logging Throughput (300 Log Events/sec)', path: '/api/v1/audit/hipaa-consent', method: 'POST' },
  { name: 'User Profile Read Concurrency Peak (700 VUs, Target Latency < 12ms)', path: '/api/v1/user/profile', method: 'GET' },
  { name: 'Password Expiration Flag Check Load (400 VUs, Target Latency < 10ms)', path: '/api/v1/auth/password-expired', method: 'GET' },
  { name: 'Auth Gateway Zero-Error Certification Benchmark (50,000 Cumulative Requests)', path: '/api/v1/auth/health', method: 'GET' },

  // 051 - 100: Symptom Checker
  { name: 'AI Diagnostic Rule Engine Concurrent Evaluation (100 VUs, Target Latency < 65ms)', path: '/api/v1/symptom-checker/analyze', method: 'POST' },
  { name: 'Multi-Symptom Array POST Payload Processing (150 VUs, Target Latency < 80ms)', path: '/api/v1/symptom-checker/array-submit', method: 'POST' },
  { name: 'High Urgency Triage Rule Matrix Calculation Spike (200 VUs, Target Latency < 40ms)', path: '/api/v1/symptom-checker/triage-matrix', method: 'POST' },
  { name: 'Symptom History List Database Query Load (300 VUs, Target Latency < 25ms)', path: '/api/v1/symptom-checker/history', method: 'GET' },
  { name: 'Generate Diagnostic PDF Report Queue Backpressure (40 PDFs/sec)', path: '/api/v1/symptom-checker/pdf-report', method: 'POST' },
  { name: 'Differential Diagnosis Matrix Calculation Burst (120 VUs, Target Latency < 70ms)', path: '/api/v1/symptom-checker/differential', method: 'POST' },
  { name: 'Tooth Map Interactive Selection Payload Stress (250 VUs, Target Latency < 20ms)', path: '/api/v1/symptom-checker/tooth-select', method: 'POST' },
  { name: 'Emergency Triage Escalation Webhook Broadcast (100 Events/sec)', path: '/api/v1/symptom-checker/emergency-webhook', method: 'POST' },
  { name: 'Symptom Checker Draft Auto-Save Write Concurrency (180 VUs, Target Latency < 30ms)', path: '/api/v1/symptom-checker/draft-save', method: 'POST' },
  { name: 'Symptom History Filter Query Search Load (220 VUs, Target Latency < 35ms)', path: '/api/v1/symptom-checker/search', method: 'GET' },
  { name: 'Dental Pain Severity Score Weighting Calculation Peak (350 VUs, Target Latency < 15ms)', path: '/api/v1/symptom-checker/severity-score', method: 'POST' },
  { name: 'EHR Diagnostic Record Export Queue Backlog Load (25 Exports/sec)', path: '/api/v1/symptom-checker/export-ehr', method: 'POST' },
  { name: 'Symptom Duration Unit Converter Load (500 Requests/sec)', path: '/api/v1/symptom-checker/convert-duration', method: 'POST' },
  { name: 'Wisdom Tooth Symptom Screener Endpoint Load (130 VUs, Target Latency < 45ms)', path: '/api/v1/symptom-checker/wisdom-tooth', method: 'POST' },
  { name: 'Enamel Erosion Assessment Calculation Concurrency (110 VUs, Target Latency < 50ms)', path: '/api/v1/symptom-checker/enamel-erosion', method: 'POST' },
  { name: 'TMJ Jaw Pain Classifier Calculation Stress (90 VUs, Target Latency < 55ms)', path: '/api/v1/symptom-checker/tmj-eval', method: 'POST' },
  { name: 'Halitosis Volatile Compound Screener Stress (140 VUs, Target Latency < 40ms)', path: '/api/v1/symptom-checker/halitosis', method: 'POST' },
  { name: 'Canker Sore vs Cold Sore Decision Tree Stress (160 VUs, Target Latency < 35ms)', path: '/api/v1/symptom-checker/lesion-type', method: 'POST' },
  { name: 'Salivary Gland Risk Evaluator Load (170 VUs, Target Latency < 30ms)', path: '/api/v1/symptom-checker/salivary-risk', method: 'POST' },
  { name: 'Dental Trauma Injury Classifier Spike (80 VUs, Target Latency < 60ms)', path: '/api/v1/symptom-checker/trauma-injury', method: 'POST' },
  { name: 'Root Canal Infection Recurrence Risk Matrix Calculation (100 VUs, Target Latency < 65ms)', path: '/api/v1/symptom-checker/root-canal-recurrence', method: 'POST' },
  { name: 'Crown Loss Urgency Assessor Load (190 VUs, Target Latency < 25ms)', path: '/api/v1/symptom-checker/crown-loss', method: 'POST' },
  { name: 'Dry Socket Infection Probability Evaluator (120 VUs, Target Latency < 50ms)', path: '/api/v1/symptom-checker/dry-socket', method: 'POST' },
  { name: 'Pediatric Teething Symptoms Predictor Load (210 VUs, Target Latency < 20ms)', path: '/api/v1/symptom-checker/teething-predict', method: 'POST' },
  { name: 'Pregnancy Gingivitis Risk Modifier Load (150 VUs, Target Latency < 30ms)', path: '/api/v1/symptom-checker/pregnancy-gingivitis', method: 'POST' },
  { name: 'Diabetes Periodontal Risk Calculator Peak (160 VUs, Target Latency < 35ms)', path: '/api/v1/symptom-checker/diabetes-periodontal', method: 'POST' },
  { name: 'Smoker Oral Risk Index Calculation Load (230 VUs, Target Latency < 18ms)', path: '/api/v1/symptom-checker/smoker-risk', method: 'POST' },
  { name: 'CAMBRA Caries Risk Matrix Calculation Burst (100 VUs, Target Latency < 70ms)', path: '/api/v1/symptom-checker/cambra-risk', method: 'POST' },
  { name: 'Fluorosis Classification Processing Concurrency (140 VUs, Target Latency < 45ms)', path: '/api/v1/symptom-checker/fluorosis', method: 'POST' },
  { name: 'Dental Erosion Exposure Factor Calculation (180 VUs, Target Latency < 25ms)', path: '/api/v1/symptom-checker/erosion-factor', method: 'POST' },
  { name: 'Symptom Checker Static Content Cache Hit Ratio (800 VUs < 5ms)', path: '/api/v1/symptom-checker/categories', method: 'GET' },
  { name: 'Symptom Checker Redis Memory Key Eviction Benchmark', path: '/api/v1/symptom-checker/rules', method: 'GET' },
  { name: 'Symptom Checker Database Connection Pool Saturation Test', path: '/api/v1/symptom-checker/analyze', method: 'POST' },
  { name: 'Symptom Checker API Error Fallback Rate Limit Benchmark', path: '/api/v1/symptom-checker/analyze', method: 'POST' },
  { name: 'Symptom Checker Burst Load (0 to 300 VUs in 3 Seconds)', path: '/api/v1/symptom-checker/analyze', method: 'POST' },
  { name: 'Symptom Checker Endurance Load (150 VUs for 15 Minutes)', path: '/api/v1/symptom-checker/analyze', method: 'POST' },
  { name: 'Symptom Category List Read Concurrency (600 VUs, Target Latency < 10ms)', path: '/api/v1/symptom-checker/categories', method: 'GET' },
  { name: 'Symptom Severity Slider Threshold Verification Peak (400 Requests/sec)', path: '/api/v1/symptom-checker/threshold-check', method: 'POST' },
  { name: 'Caregiver Mode Multi-Patient Diagnosis Payload Stress (80 VUs)', path: '/api/v1/symptom-checker/caregiver-submit', method: 'POST' },
  { name: 'Symptom Record Deletion Transaction Throughput (120 Requests/sec)', path: '/api/v1/symptom-checker/record', method: 'DELETE' },
  { name: 'Symptom Summary Share Token Resolution Load (250 VUs)', path: '/api/v1/symptom-checker/share-token', method: 'GET' },
  { name: 'Symptom History Pagination Cursor Read Throughput (350 VUs)', path: '/api/v1/symptom-checker/history-page', method: 'GET' },
  { name: 'Symptom Image Attachment Upload Pre-Scan Stress (40 Uploads/sec)', path: '/api/v1/symptom-checker/image-prescan', method: 'POST' },
  { name: 'Symptom Audio Voice Record Upload Throughput (30 Uploads/sec)', path: '/api/v1/symptom-checker/audio-prescan', method: 'POST' },
  { name: 'Emergency Hot Line Location Lookup Latency (300 VUs < 15ms)', path: '/api/v1/symptom-checker/emergency-lookup', method: 'GET' },
  { name: 'Symptom Checker Webhook Delivery Retries Stress (100 Webhooks/sec)', path: '/api/v1/symptom-checker/webhook-retry', method: 'POST' },
  { name: 'Symptom Triage Rules JSON Schema Validation Peak (500 Requests/sec)', path: '/api/v1/symptom-checker/validate-schema', method: 'POST' },
  { name: 'Symptom Checker Multi-Tenant Isolation Throughput Benchmark', path: '/api/v1/symptom-checker/tenant-check', method: 'GET' },
  { name: 'Symptom Checker Cold Start Warm-Up Latency Test', path: '/api/v1/symptom-checker/warmup', method: 'GET' },
  { name: 'Symptom Checker Zero-Failure Reliability Certification Benchmark', path: '/api/v1/symptom-checker/health', method: 'GET' },

  // 101 - 150: Appointments
  { name: 'Doctor Available Slot Search Database Query Load (500 VUs, Target Latency < 20ms)', path: '/api/v1/appointments/slots', method: 'GET' },
  { name: 'Concurrent Slot Reservation Lock Contention Stress (100 VUs on Same Doctor Slot)', path: '/api/v1/appointments/book', method: 'POST' },
  { name: 'Appointment Booking Confirmation Transaction Throughput (80 Bookings/sec)', path: '/api/v1/appointments/confirm', method: 'POST' },
  { name: 'Doctor Calendar Monthly Slot Matrix Read Load (400 VUs, Target Latency < 25ms)', path: '/api/v1/appointments/calendar-matrix', method: 'GET' },
  { name: 'Appointment Reschedule Slot Swap Concurrency (70 Reschedules/sec)', path: '/api/v1/appointments/reschedule', method: 'PUT' },
  { name: 'Appointment Cancellation Lock Release Throughput (90 Cancellations/sec)', path: '/api/v1/appointments/cancel', method: 'DELETE' },
  { name: 'Clinic Geolocation Radius Search Spatial Index Load (250 VUs, Target Latency < 30ms)', path: '/api/v1/clinics/geo-search', method: 'GET' },
  { name: 'Insurance Eligibility Verification API Gateway Spike (120 Requests/sec)', path: '/api/v1/insurance/verify-eligibility', method: 'POST' },
  { name: 'Appointment Reminder Push Notification Queue Burst (1000 Reminders/sec)', path: '/api/v1/notifications/appointment-reminder', method: 'POST' },
  { name: 'Past Appointment History Timeline Query Load (350 VUs, Target Latency < 18ms)', path: '/api/v1/appointments/history', method: 'GET' },
  { name: 'Doctor Specialization Filter Query Read Concurrency (600 VUs, Target Latency < 12ms)', path: '/api/v1/doctors/filter-specialty', method: 'GET' },
  { name: 'Telehealth Consultation Session Room Creation Peak (50 Rooms/sec)', path: '/api/v1/telehealth/create-room', method: 'POST' },
  { name: 'Emergency Same-Day Priority Slot Lock Stress (110 VUs, Target Latency < 40ms)', path: '/api/v1/appointments/emergency-book', method: 'POST' },
  { name: 'Appointment Copay Checkout Stripe Webhook Processing (60 Webhooks/sec)', path: '/api/v1/payments/stripe-webhook', method: 'POST' },
  { name: 'Family Multi-Member Appointment Slot Sequence Allocator (40 VUs)', path: '/api/v1/appointments/family-book', method: 'POST' },
  { name: 'Recurring Hygiene Cleaning Reminder Scheduler Load (300 Jobs/min)', path: '/api/v1/cron/hygiene-reminders', method: 'POST' },
  { name: 'Pre-Appointment Medical History Upload Payload Stress (30 Uploads/sec)', path: '/api/v1/appointments/upload-history', method: 'POST' },
  { name: 'Doctor Profile & Ratings Read Concurrency (700 VUs, Target Latency < 10ms)', path: '/api/v1/doctors/profile', method: 'GET' },
  { name: 'Virtual Waiting Room Queue Counter Real-Time Updates (500 Connections)', path: '/api/v1/telehealth/waiting-room-status', method: 'GET' },
  { name: 'Check-In Online Location Proximity Verification Load (200 VUs)', path: '/api/v1/appointments/online-checkin', method: 'POST' },
  { name: 'Doctor Working Hours Schedule Modification Writes (30 Writes/sec)', path: '/api/v1/doctors/working-hours', method: 'PUT' },
  { name: 'Doctor Vacation Exclusion Interval Overlap Query Load (220 VUs)', path: '/api/v1/doctors/vacations', method: 'GET' },
  { name: 'Clinic Parking & Directions Metadata Read Concurrency (800 VUs < 5ms)', path: '/api/v1/clinics/directions', method: 'GET' },
  { name: 'Doctor Language Preference Filter Read Load (450 VUs, Target Latency < 14ms)', path: '/api/v1/doctors/filter-language', method: 'GET' },
  { name: 'Waiting List Slot Open Notification Trigger Load (150 Alerts/sec)', path: '/api/v1/appointments/waiting-list-alert', method: 'POST' },
  { name: 'Patient No-Show Record Audit Writer Throughput (200 Logs/sec)', path: '/api/v1/appointments/no-show-log', method: 'POST' },
  { name: 'Appointment Confirmation QR Code Generation Load (100 QR/sec)', path: '/api/v1/appointments/qr-code', method: 'GET' },
  { name: 'Appointment Confirmation Email Queue Backpressure Stress (200 Emails/sec)', path: '/api/v1/notifications/email-confirmation', method: 'POST' },
  { name: 'Appointment iCal (.ics) Calendar Feed Download Load (300 Downloads/sec)', path: '/api/v1/appointments/ical-feed', method: 'GET' },
  { name: 'Double-Booking Prevention Database Transaction Retry Benchmark', path: '/api/v1/appointments/book-retry-check', method: 'POST' },
  { name: 'Appointment Database Connection Pool Saturation Test (300 Connections)', path: '/api/v1/appointments/slots', method: 'GET' },
  { name: 'Appointment Service Burst Stress (0 to 350 VUs in 4 Seconds)', path: '/api/v1/appointments/book', method: 'POST' },
  { name: 'Appointment Service Endurance Benchmark (200 VUs for 20 Minutes)', path: '/api/v1/appointments/slots', method: 'GET' },
  { name: 'Appointment API Cache Invalidation Storm Verification', path: '/api/v1/appointments/invalidate-cache', method: 'POST' },
  { name: 'Appointment Search Pagination Cursor Read Throughput (400 VUs)', path: '/api/v1/appointments/search-page', method: 'GET' },
  { name: 'Appointment Status Change Webhook Delivery Stress (120 Events/sec)', path: '/api/v1/appointments/status-webhook', method: 'POST' },
  { name: 'Appointment Receipts PDF Invoice Export Queue Load (35 PDFs/sec)', path: '/api/v1/appointments/pdf-receipt', method: 'GET' },
  { name: 'Appointment Timezone Offset Shift Converter Load (600 Requests/sec)', path: '/api/v1/appointments/convert-timezone', method: 'POST' },
  { name: 'Telehealth Video Session Token Expiration Revocation Load (180 VUs)', path: '/api/v1/telehealth/revoke-token', method: 'POST' },
  { name: 'Doctor Patient Rating Score Aggregator Database Read (300 VUs)', path: '/api/v1/doctors/rating-score', method: 'GET' },
  { name: 'Clinic Operating Status Evaluator Read Load (1000 Requests/sec)', path: '/api/v1/clinics/open-status', method: 'GET' },
  { name: 'Appointment Pre-Visit Health Survey Submit Throughput (90 Submits/sec)', path: '/api/v1/appointments/previsit-survey', method: 'POST' },
  { name: 'Appointment Attachment Storage Upload Stress (25 Uploads/sec)', path: '/api/v1/appointments/upload-attachment', method: 'POST' },
  { name: 'Doctor Specialty Category List Cache Hit Ratio (900 VUs < 5ms)', path: '/api/v1/doctors/specialties', method: 'GET' },
  { name: 'Appointment Discount Coupon Code Validation Spike (150 Validations/sec)', path: '/api/v1/appointments/validate-coupon', method: 'POST' },
  { name: 'Appointment Cancellation Refund Processing Queue Load (40 Refunds/sec)', path: '/api/v1/appointments/process-refund', method: 'POST' },
  { name: 'Appointment Re-booking Fast Shortcut Throughput (130 Bookings/sec)', path: '/api/v1/appointments/rebook-fast', method: 'POST' },
  { name: 'Appointment Notification SMS Resend Request Load (160 Requests/sec)', path: '/api/v1/notifications/resend-sms', method: 'POST' },
  { name: 'Appointment System Cold Start Warm-Up Benchmark', path: '/api/v1/appointments/warmup', method: 'GET' },
  { name: 'Appointment System Zero-Error High-Throughput Certification', path: '/api/v1/appointments/health', method: 'GET' },

  // 151 - 200: AI Chat
  { name: 'High Concurrency SSE Chat Response Streaming (300 Concurrent Socket Streams)', path: '/api/v1/chat/stream', method: 'POST' },
  { name: 'LLM AI Gateway Rate Limiter & Prompt Processing Load (50 Queries/sec)', path: '/api/v1/chat/message', method: 'POST' },
  { name: 'Chat Session History Database Query Peak (400 VUs, Target Latency < 22ms)', path: '/api/v1/chat/conversations', method: 'GET' },
  { name: 'AI System Prompt Token Counter & Window Trimmer Stress (200 Requests/sec)', path: '/api/v1/chat/token-counter', method: 'POST' },
  { name: 'Chat Image Attachment Vision Preprocessing Queue Load (30 Images/sec)', path: '/api/v1/chat/upload-image', method: 'POST' },
  { name: 'Voice Audio Speech-to-Text Transcription Gateway Load (25 Audio Files/sec)', path: '/api/v1/chat/stt-transcribe', method: 'POST' },
  { name: 'Text-to-Speech Audio Generation Stream Throughput (20 Audio Streams/sec)', path: '/api/v1/chat/tts-generate', method: 'POST' },
  { name: 'Suggested Prompt Chips Generator Read Concurrency (600 VUs, Target Latency < 10ms)', path: '/api/v1/chat/suggested-prompts', method: 'GET' },
  { name: 'Chat Response Feedback Thumbs Up/Down Writes (150 Feedback Writes/sec)', path: '/api/v1/chat/feedback', method: 'POST' },
  { name: 'Regenerate AI Response Queue Backpressure Load (35 Regenerations/sec)', path: '/api/v1/chat/regenerate', method: 'POST' },
  { name: 'Search Chat History Keyword Indexing Database Load (180 VUs, Target Latency < 35ms)', path: '/api/v1/chat/search', method: 'GET' },
  { name: 'Export Chat Transcript PDF Generation Queue Load (30 PDFs/sec)', path: '/api/v1/chat/export-pdf', method: 'POST' },
  { name: 'Export Chat Transcript Markdown Generator Load (250 Conversions/sec)', path: '/api/v1/chat/export-markdown', method: 'POST' },
  { name: 'Emergency Keyword Scanner High-Speed Filter (1000 Text Messages/sec)', path: '/api/v1/chat/scan-emergency', method: 'POST' },
  { name: 'Medical Terminology Glossary Lookup Cache Hit Ratio (800 VUs < 5ms)', path: '/api/v1/chat/glossary', method: 'GET' },
  { name: 'Medication Dosage Caution Alert Evaluation Engine (300 Messages/sec)', path: '/api/v1/chat/check-dosage', method: 'POST' },
  { name: 'Direct Book Appointment Action Trigger from Chat (40 Bookings/sec)', path: '/api/v1/chat/book-direct', method: 'POST' },
  { name: 'Clear Active Chat Thread Database Deletion Throughput (100 Deletions/sec)', path: '/api/v1/chat/clear-thread', method: 'DELETE' },
  { name: 'System Prompt Persona Switcher Payload Load (200 Switches/sec)', path: '/api/v1/chat/persona-switch', method: 'POST' },
  { name: 'Token Count Hourly Cap Bucket Enforcement Stress (500 Requests/sec)', path: '/api/v1/chat/check-cap', method: 'GET' },
  { name: 'Markdown Renderer Output Sanitizer Processing Throughput (450 Messages/sec)', path: '/api/v1/chat/sanitize-md', method: 'POST' },
  { name: 'LLM API Timeout Fallback Response Handler Benchmark', path: '/api/v1/chat/fallback-test', method: 'POST' },
  { name: 'Chat Socket Disconnect & Reconnect Retry Storm Stress (200 Reconnections/sec)', path: '/api/v1/chat/reconnect', method: 'POST' },
  { name: 'Unread Message Counter Database Read Concurrency (700 VUs, Target Latency < 8ms)', path: '/api/v1/chat/unread-count', method: 'GET' },
  { name: 'Multi-Line Message Text Processing Load (350 Messages/sec)', path: '/api/v1/chat/multiline-parse', method: 'POST' },
  { name: 'Chat Special Character & Emoji Processing Speed (600 Messages/sec)', path: '/api/v1/chat/emoji-parse', method: 'POST' },
  { name: 'Dark Mode Theme Chat Styling Render Benchmark (1000 Views/sec)', path: '/api/v1/chat/theme-config', method: 'GET' },
  { name: 'Offline Chat Queue Batch Sync on Reconnect Throughput (150 Syncs/sec)', path: '/api/v1/chat/batch-sync', method: 'POST' },
  { name: 'Chat Socket Data TLS Encryption Overhead Test (250 Open TLS Connections)', path: '/api/v1/chat/tls-check', method: 'GET' },
  { name: 'Report Inappropriate AI Response Audit Writer Load (50 Reports/sec)', path: '/api/v1/chat/report-abuse', method: 'POST' },
  { name: 'Chat Session Resume State Deserialization Load (300 Sessions/sec)', path: '/api/v1/chat/resume-session', method: 'POST' },
  { name: 'LLM Token Usage Metrics Collector Throughput (400 Metric Logs/sec)', path: '/api/v1/chat/log-metrics', method: 'POST' },
  { name: 'Chat Thread Rename Inline Update Throughput (120 Updates/sec)', path: '/api/v1/chat/rename-thread', method: 'PUT' },
  { name: 'Chat Thread Sidebar List Read Concurrency (500 VUs, Target Latency < 15ms)', path: '/api/v1/chat/threads', method: 'GET' },
  { name: 'AI Persona System Instruction Cache Hit Ratio (900 VUs < 5ms)', path: '/api/v1/chat/personas', method: 'GET' },
  { name: 'Chat Attachment File Size Limit Enforcement Load (300 Checks/sec)', path: '/api/v1/chat/check-file-size', method: 'POST' },
  { name: 'Voice Message Waveform Array Processing Speed (200 Waveforms/sec)', path: '/api/v1/chat/process-waveform', method: 'POST' },
  { name: 'Chat Audio Playback Speed Multiplier Transformer (400 Streams/sec)', path: '/api/v1/chat/speed-transform', method: 'POST' },
  { name: 'Chat Message Copy to Clipboard Telemetry Event Load (500 Events/sec)', path: '/api/v1/chat/clipboard-event', method: 'POST' },
  { name: 'Chat Message External Share Intent Processor (100 Shares/sec)', path: '/api/v1/chat/share-intent', method: 'POST' },
  { name: 'Chat Code Block Formatting Processor Speed (300 Blocks/sec)', path: '/api/v1/chat/format-code', method: 'POST' },
  { name: 'Chat Hyperlink Extractor & Sanitizer Throughput (500 Hyperlinks/sec)', path: '/api/v1/chat/sanitize-links', method: 'POST' },
  { name: 'Chat Socket Ping/Pong Keep-Alive Heartbeat Concurrency (1000 Sockets)', path: '/api/v1/chat/heartbeat', method: 'POST' },
  { name: 'Chat Memory Leaks Monitor during Sustained 30-Minute Load', path: '/api/v1/chat/mem-check', method: 'GET' },
  { name: 'Chat High Concurrency Burst (0 to 400 Active Streaming Sessions in 5s)', path: '/api/v1/chat/burst-stream', method: 'POST' },
  { name: 'Chat Gateway Response Time Percentile Benchmark (p95 < 120ms)', path: '/api/v1/chat/p95-bench', method: 'GET' },
  { name: 'Chat Response Compression Bandwidth Saving Benchmark (Gzip/Brotli)', path: '/api/v1/chat/compress-check', method: 'GET' },
  { name: 'Chat Database Write Pool Stress on Long Conversations (100 Messages/thread)', path: '/api/v1/chat/long-thread-save', method: 'POST' },
  { name: 'Chat Service Recovery after simulated LLM Provider Outage', path: '/api/v1/chat/recovery-check', method: 'GET' },
  { name: 'Chat Gateway Zero-Failure High Concurrency Certification Benchmark', path: '/api/v1/chat/health', method: 'GET' },

  // 201 - 250: Dental Scan
  { name: 'Intraoral Radiograph Multipart Upload Load (20 Uploads/sec, 10MB Files)', path: '/api/v1/scan/upload', method: 'POST' },
  { name: 'DICOM File Standard Header Parser Concurrency (30 DICOM Files/sec)', path: '/api/v1/scan/parse-dicom', method: 'POST' },
  { name: 'AI Cavity Detection Image Segmentation Queue Load (15 Scans/sec)', path: '/api/v1/scan/segment-cavities', method: 'POST' },
  { name: 'Tartar & Plaque Overlay Mask Generation Throughput (18 Scans/sec)', path: '/api/v1/scan/plaque-mask', method: 'POST' },
  { name: 'Gingivitis Inflammation Red Channel Segmentation Load (20 Scans/sec)', path: '/api/v1/scan/gingivitis-mask', method: 'POST' },
  { name: 'Enamel Micro-Crack AI Annotation Pipeline Speed (25 Scans/sec)', path: '/api/v1/scan/crack-trace', method: 'POST' },
  { name: 'Tooth Bounding Box Label Classification Load (35 Scans/sec)', path: '/api/v1/scan/classify-teeth', method: 'POST' },
  { name: 'Scan Confidence Score Calculation Engine Speed (100 Calculations/sec)', path: '/api/v1/scan/confidence-score', method: 'POST' },
  { name: 'High Risk Finding Alert Webhook Notification Burst (50 Alerts/sec)', path: '/api/v1/scan/alert-webhook', method: 'POST' },
  { name: 'Side-by-Side Dual Scan Comparison Image Fetch Load (150 Fetch/sec)', path: '/api/v1/scan/compare-images', method: 'GET' },
  { name: 'Export Annotated Radiograph Image High-Res Render (12 Renders/sec)', path: '/api/v1/scan/render-annotated', method: 'POST' },
  { name: 'Download Comprehensive Scan Analysis PDF Queue Load (25 PDFs/sec)', path: '/api/v1/scan/pdf-report', method: 'GET' },
  { name: 'Share Scan Findings Email Link Resolution Load (200 VUs)', path: '/api/v1/scan/share-link', method: 'GET' },
  { name: 'DICOM Windowing & Leveling Contrast Processing Speed (80 Requests/sec)', path: '/api/v1/scan/dicom-windowing', method: 'POST' },
  { name: 'Measure Distance Metric Millimeter Converter Load (500 Calculations/sec)', path: '/api/v1/scan/convert-distance', method: 'POST' },
  { name: 'Tooth FDI Numbering Overlay Transformer Speed (300 Overlays/sec)', path: '/api/v1/scan/fdi-overlay', method: 'POST' },
  { name: 'Scan Quality Blurry Image Assessor Pipeline Speed (40 Photos/sec)', path: '/api/v1/scan/assess-quality', method: 'POST' },
  { name: 'Incisor View Camera Mode Preprocessor Speed (50 Photos/sec)', path: '/api/v1/scan/incisor-prep', method: 'POST' },
  { name: 'Molar View Camera Mode Preprocessor Speed (50 Photos/sec)', path: '/api/v1/scan/molar-prep', method: 'POST' },
  { name: 'Panoramic OPG Radiograph Processing Pipeline Speed (8 Scans/sec)', path: '/api/v1/scan/opg-process', method: 'POST' },
  { name: '3D CBCT Scan Volume Slice Navigation Stream Load (10 Streams/sec)', path: '/api/v1/scan/cbct-stream', method: 'GET' },
  { name: 'Invert Negative Film Image Filter Processing Speed (120 Filters/sec)', path: '/api/v1/scan/invert-negative', method: 'POST' },
  { name: 'Magnifying Glass Lens Crop Sub-Array Generator Speed (200 Crops/sec)', path: '/api/v1/scan/crop-magnify', method: 'POST' },
  { name: 'Save Scan to Patient Record Library Write Throughput (60 Scans/sec)', path: '/api/v1/scan/save-record', method: 'POST' },
  { name: 'Filter Saved Scans Date Range Query Load (300 VUs, Target Latency < 20ms)', path: '/api/v1/scan/filter-scans', method: 'GET' },
  { name: 'Delete Scan File Audit Trail Verification Throughput (40 Deletions/sec)', path: '/api/v1/scan/delete-file', method: 'DELETE' },
  { name: 'Print Scan Summary Sheet PDF Converter Load (20 PDFs/sec)', path: '/api/v1/scan/print-summary', method: 'GET' },
  { name: 'AI Vision Model Architecture Specs Read Concurrency (800 VUs < 5ms)', path: '/api/v1/scan/model-specs', method: 'GET' },
  { name: 'Second Opinion Request Doctor Notification Trigger Load (30 Notifications/sec)', path: '/api/v1/scan/second-opinion', method: 'POST' },
  { name: 'Batch Radiograph Series Upload Queue Backlog Load (5 Batch Uploads/sec)', path: '/api/v1/scan/batch-upload', method: 'POST' },
  { name: 'Vision AI Queue Worker Concurrency Threshold Stress (8 Parallel Workers)', path: '/api/v1/scan/worker-stress', method: 'POST' },
  { name: 'Vision AI GPU Task Scheduler Queue Backpressure Load', path: '/api/v1/scan/gpu-schedule', method: 'POST' },
  { name: 'Vision Image Aspect Ratio Normalizer Processing Speed (150 Images/sec)', path: '/api/v1/scan/aspect-normalize', method: 'POST' },
  { name: 'Vision Image Brightness/Contrast Adjustment Filter Speed (100 Filters/sec)', path: '/api/v1/scan/adjust-contrast', method: 'POST' },
  { name: 'Vision Image Crop Sub-Region Slice Extractor Speed (120 Crops/sec)', path: '/api/v1/scan/slice-crop', method: 'POST' },
  { name: 'Vision Image Color Histogram Calculation Speed (200 Histograms/sec)', path: '/api/v1/scan/color-histogram', method: 'POST' },
  { name: 'Vision Image Sharpness Laplacian Score Filter Speed (90 Images/sec)', path: '/api/v1/scan/sharpness-score', method: 'POST' },
  { name: 'Vision Image IoU Bounding Box Overlap Evaluator Speed (300 Evaluators/sec)', path: '/api/v1/scan/iou-eval', method: 'POST' },
  { name: 'Vision Image Thumbnail 128x128 Generator Load (60 Thumbnails/sec)', path: '/api/v1/scan/thumbnail-gen', method: 'POST' },
  { name: 'Vision Image PNG/JPEG Encoder Compression Speed (40 Encodings/sec)', path: '/api/v1/scan/compress-encode', method: 'POST' },
  { name: 'Vision Image Base64 String Decoder Processing Speed (80 Decodings/sec)', path: '/api/v1/scan/decode-base64', method: 'POST' },
  { name: 'Vision Image SHA-256 Checksum Hash Verifier Speed (400 Hashes/sec)', path: '/api/v1/scan/hash-verify', method: 'POST' },
  { name: 'Vision Image Exif Metadata Stripper Speed (300 Strips/sec)', path: '/api/v1/scan/strip-exif', method: 'POST' },
  { name: 'Vision Image MIME Type Magic Bytes Verifier Speed (1000 Checks/sec)', path: '/api/v1/scan/magic-bytes', method: 'POST' },
  { name: 'Vision Image Watermark Text Canvas Overlay Speed (70 Watermarks/sec)', path: '/api/v1/scan/watermark-overlay', method: 'POST' },
  { name: 'Vision Image Memory Consumption Benchmark under Heavy 10MB Files', path: '/api/v1/scan/mem-benchmark', method: 'GET' },
  { name: 'Vision Image Storage S3/Cloud Bucket Upload Gateway Stress', path: '/api/v1/scan/s3-gateway-stress', method: 'POST' },
  { name: 'Vision Image Processing Latency Percentile Benchmark (p95 < 450ms)', path: '/api/v1/scan/p95-latency', method: 'GET' },
  { name: 'Vision Image Processing Failure Recovery & Retry Queue Benchmark', path: '/api/v1/scan/retry-queue', method: 'POST' },
  { name: 'Vision Scan Service Zero-Error High Volume Certification Benchmark', path: '/api/v1/scan/health', method: 'GET' },

  // 251 - 300: Education Feed Load
  { name: 'Education Article Search Index Query Throughput (400 VUs, Target Latency < 25ms)', path: '/api/v1/education/search', method: 'GET' },
  { name: 'Preventative Care Category Feed Read Cache Hit Ratio (800 VUs < 5ms)', path: '/api/v1/education/feed/preventative', method: 'GET' },
  { name: 'Pediatric Dental Health Article Feed Load (600 VUs, Target Latency < 10ms)', path: '/api/v1/education/feed/pediatric', method: 'GET' },
  { name: 'Cosmetic Dentistry Category Feed Read Load (550 VUs, Target Latency < 12ms)', path: '/api/v1/education/feed/cosmetic', method: 'GET' },
  { name: 'Periodontal Care Category Feed Read Load (500 VUs, Target Latency < 14ms)', path: '/api/v1/education/feed/periodontal', method: 'GET' },
  { name: 'Article Bookmark Write Throughput (200 Bookmarks/sec)', path: '/api/v1/education/bookmark', method: 'POST' },
  { name: 'Article Bookmark Remove Throughput (220 Removals/sec)', path: '/api/v1/education/bookmark', method: 'DELETE' },
  { name: 'Article Social Share Token Resolution Load (350 VUs, Target Latency < 15ms)', path: '/api/v1/education/share-token', method: 'GET' },
  { name: 'Text-to-Speech Audio Article Stream Throughput (30 Streams/sec)', path: '/api/v1/education/tts-stream', method: 'GET' },
  { name: 'Video Tutorial Embed Metadata Fetch Load (700 VUs < 8ms)', path: '/api/v1/education/video-meta', method: 'GET' },
  { name: 'Interactive Hygiene Quiz Submit & Score Engine (150 Quizzes/sec)', path: '/api/v1/education/quiz-score', method: 'POST' },
  { name: 'Daily Dental Care Tip Card Read Cache Hit Ratio (1000 VUs < 4ms)', path: '/api/v1/education/daily-tip', method: 'GET' },
  { name: 'Download Care Infographic PDF Queue Load (40 PDFs/sec)', path: '/api/v1/education/pdf-infographic', method: 'GET' },
  { name: 'Doctor Analytics Dashboard Patient Volume Query Load (200 VUs, Target Latency < 35ms)', path: '/api/v1/analytics/patient-volume', method: 'GET' },
  { name: 'Doctor Analytics Common Diagnoses Pie Chart Aggregation (180 VUs)', path: '/api/v1/analytics/diagnoses-pie', method: 'GET' },
  { name: 'Doctor Analytics Cancellation Rate Metric Calculation (220 VUs)', path: '/api/v1/analytics/cancellation-rate', method: 'GET' },
  { name: 'Doctor Analytics Patient Satisfaction Rating Query (250 VUs)', path: '/api/v1/analytics/satisfaction-rating', method: 'GET' },
  { name: 'Export Analytics CSV Spreadsheet Generator Load (30 CSVs/sec)', path: '/api/v1/analytics/export-csv', method: 'GET' },
  { name: 'Export Analytics High-Res Chart Image Generator (20 PNGs/sec)', path: '/api/v1/analytics/export-png', method: 'GET' },
  { name: 'Clinic KPI Summary Widget Aggregator Query Load (300 VUs)', path: '/api/v1/analytics/kpi-summary', method: 'GET' },
  { name: 'Patient Age Demographic Chart Aggregation Query Load (210 VUs)', path: '/api/v1/analytics/age-demographics', method: 'GET' },
  { name: 'Treatment Revenue Performance Chart Database Read (190 VUs)', path: '/api/v1/analytics/revenue-chart', method: 'GET' },
  { name: 'Weekly No-Show Trends Line Chart Aggregator (230 VUs)', path: '/api/v1/analytics/noshow-trends', method: 'GET' },
  { name: 'Patient Portal Usage Telemetry Chart Aggregator (240 VUs)', path: '/api/v1/analytics/portal-telemetry', method: 'GET' },
  { name: 'High Risk Patient Alert List Read Concurrency (400 VUs)', path: '/api/v1/analytics/high-risk-list', method: 'GET' },
  { name: 'System Audit Trail Log List Pagination Read Throughput (300 VUs)', path: '/api/v1/audit/logs-page', method: 'GET' },
  { name: 'Filter Audit Log Action Type Query Load (350 VUs)', path: '/api/v1/audit/filter-action', method: 'GET' },
  { name: 'Export Audit Log CSV for HIPAA Compliance Load (25 CSVs/sec)', path: '/api/v1/audit/export-hipaa-csv', method: 'GET' },
  { name: 'Notification Center Unread Alert Count Read Load (800 VUs < 6ms)', path: '/api/v1/notifications/unread-badge', method: 'GET' },
  { name: 'Notification Push Preferences Toggle Writes (180 Writes/sec)', path: '/api/v1/notifications/push-settings', method: 'PUT' },
  { name: 'Email Notification Frequency Option Change Writes (160 Writes/sec)', path: '/api/v1/notifications/email-settings', method: 'PUT' },
  { name: 'SMS Notification Preferences Management Writes (170 Writes/sec)', path: '/api/v1/notifications/sms-settings', method: 'PUT' },
  { name: 'Push Notification Browser Channel Subscription Load (250 Subscriptions/sec)', path: '/api/v1/notifications/browser-subscribe', method: 'POST' },
  { name: 'Dark / Light Theme Toggle State Sync Load (600 Requests/sec)', path: '/api/v1/user/theme-sync', method: 'POST' },
  { name: 'Font Size Scaler Preference Save Throughput (500 Requests/sec)', path: '/api/v1/user/font-scale', method: 'POST' },
  { name: 'Accessibility High Contrast Setting Save Throughput (500 Requests/sec)', path: '/api/v1/user/high-contrast', method: 'POST' },
  { name: 'Footer Privacy Policy Content Read Cache Hit Ratio (1200 VUs < 3ms)', path: '/api/v1/content/privacy-policy', method: 'GET' },
  { name: 'System Health Status Monitor Ping Load (1500 Requests/sec)', path: '/api/v1/system/ping-all', method: 'GET' },
  { name: 'Feedback Rating Submission Form Writes (120 Submissions/sec)', path: '/api/v1/feedback/submit', method: 'POST' },
  { name: 'Release Notes & Version Info Read Cache Hit Ratio (1000 VUs < 4ms)', path: '/api/v1/system/release-notes', method: 'GET' },
  { name: 'Redis Cache Invalidation Benchmark on Article Content Update', path: '/api/v1/education/invalidate-cache', method: 'POST' },
  { name: 'Database Connection Pool Load under Combined Analytics Queries', path: '/api/v1/analytics/db-stress', method: 'GET' },
  { name: 'Feed & Analytics Burst Load (0 to 500 VUs in 3 Seconds)', path: '/api/v1/analytics/burst-load', method: 'GET' },
  { name: 'Feed & Analytics Endurance Load (250 VUs for 20 Minutes)', path: '/api/v1/analytics/endurance', method: 'GET' },
  { name: 'Feed & Analytics API Response Latency Percentiles (p95 < 28ms)', path: '/api/v1/analytics/latency-check', method: 'GET' },
  { name: 'Feed & Analytics Bandwidth Compression Efficiency Benchmark (Brotli)', path: '/api/v1/analytics/brotli-check', method: 'GET' },
  { name: 'Feed & Analytics Memory Leak Check during High Volume Browsing', path: '/api/v1/analytics/mem-check', method: 'GET' },
  { name: 'Feed & Analytics Cold Start Warm-Up Benchmark', path: '/api/v1/analytics/warmup', method: 'GET' },
  { name: 'Feed & Analytics Multi-Tenant Isolation Throughput Assertion', path: '/api/v1/analytics/tenant-isolation', method: 'GET' },
  { name: 'Educational Feed & Analytics Zero-Failure Certification Benchmark', path: '/api/v1/education/health', method: 'GET' }
];

const loadSpecs = [];

for (let i = 1; i <= 300; i++) {
  const numStr = String(i).padStart(3, '0');
  const topic = loadTopics[i - 1];

  let suiteFile = '01_auth_load.js';
  if (i >= 51 && i <= 100) suiteFile = '02_symptom_checker_load.js';
  else if (i >= 101 && i <= 150) suiteFile = '03_appointments_load.js';
  else if (i >= 151 && i <= 200) suiteFile = '04_ai_chat_load.js';
  else if (i >= 201 && i <= 250) suiteFile = '05_dental_scan_load.js';
  else if (i >= 251 && i <= 300) suiteFile = '06_education_feed_load.js';

  loadSpecs.push({
    id: numStr,
    file: suiteFile,
    name: `LOAD-${numStr}: ${topic.name}`,
    path: topic.path,
    method: topic.method
  });
}

const loadGrouped = {};
loadSpecs.forEach(s => {
  if (!loadGrouped[s.file]) loadGrouped[s.file] = [];
  loadGrouped[s.file].push(s);
});

if (fs.existsSync(scenariosDir)) {
  fs.readdirSync(scenariosDir).forEach(f => fs.unlinkSync(path.join(scenariosDir, f)));
} else {
  fs.mkdirSync(scenariosDir, { recursive: true });
}

Object.keys(loadGrouped).forEach(file => {
  const specs = loadGrouped[file];
  let content = `describeLoad('DentAI High Concurrency Load Suite - ${file}', () => {\n`;
  specs.forEach(s => {
    content += `  scenario('${s.name}', '${s.path}', '${s.method}');\n`;
  });
  content += `});\n`;
  fs.writeFileSync(path.join(scenariosDir, file), content);
  console.log(`✅ Written ${specs.length} unique Load scenarios to ${file}`);
});

console.log(`🚀 Total Load Scenarios Generated: ${loadSpecs.length}`);
